apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-machine-learning
  template:
    metadata:
      labels:
        app: immich-machine-learning
    spec:
      containers:
      - name: immich-machine-learning
        image: ghcr.io/immich-app/immich-machine-learning:v1.132.3
        ports:
        - containerPort: 3003
          name: http
        env:
        - name: MACHINE_LEARNING_CACHE_FOLDER
          value: /cache
        volumeMounts:
        - name: model-cache
          mountPath: /cache
      volumes:
      - name: model-cache
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
spec:
  type: ClusterIP
  selector:
    app: immich-machine-learning
  ports:
  - port: 3003
    targetPort: 3003
