apiVersion: v1
kind: Secret
metadata:
  name: immich
type: Opaque
stringData:
  DB_HOSTNAME: immich-db
  DB_DATABASE_NAME: immich
  DB_USERNAME: immich
  DB_PASSWORD: immich
  REDIS_HOSTNAME: immich-redis
