apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-initialize
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: create-db
          image: postgres:16-alpine
          envFrom:
            - secretRef:
                name: postgres
          command:
            - sh
            - -c
            - |
              export PGPASSWORD=${POSTGRES_PASSWORD}
              psql -h postgres -U ${POSTGRES_USER} -c "CREATE DATABASE memos" || true