apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ente
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/wndnjs0/my-k3s-temp.git
    targetRevision: HEAD
    path: manifests/ente
  destination:
    server: https://kubernetes.default.svc
    namespace: ente
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
