apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://dl.gitea.com/charts
    chart: gitea
    targetRevision: 12.6.0
    helm:
      values: |
        gitea:
          admin:
            existingSecret: gitea-secrets
          config:
            server:
              DOMAIN: git.jmly.me
              ROOT_URL: https://git.jmly.me
            database:
              DB_TYPE: sqlite3
            service:
              DISABLE_REGISTRATION: true
              REQUIRE_SIGNIN_VIEW: true
        deployment:
          env:
          - name: GITEA____APP_NAME
            value: "Private Git"
        service:
          http:
            type: ClusterIP
            port: 3000
          ssh:
            type: ClusterIP
            port: 22
        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: git.jmly.me
              paths:
                - path: /
        persistence:
          enabled: true
          size: 200Gi
        postgresql:
          enabled: false
        postgresql-ha:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true