apiVersion: v1
kind: Secret
metadata:
  name: gitea-secrets
  namespace: gitea
type: Opaque
stringData:
  username: juuuwon2
  password: sksmsAnsdj123!
  email: "juuuwon2@gmail.com"
  passwordMode: keepUpdated