---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs
  namespace: rustfs
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgAhnMzyh0qX+g6W2Qt8QyIX4De6wYbMM8EHNmrrFDInYcP4ZZbfgNJ+O01q3tmp9t/g5JTFnZesi/AOPeW6/vqSaahncyMgARDoa3ijVpGxt3nFpYc1d15/notgWuQ3ht9EP1J4+Dryneq4RtGsh0NVt2UHxbyMT+P8wiYCiSGbraMBAKy4G+OruhBa/yCGFt8GfY5Q2uhoOxbgrdywBpsAG4tTWGvBLRMYdSN3GA6AnIndwEgoAS3qX7XG/Q6IfYKO70S+INPpGG5iQf88/ZRdyPvtO99oy0L2c2X3FlVlm2DuUAtm0HcqQaWe0oakIQfRZTn5rwNuq4BNtrrnnN9BUuQwIdDm6y2PsiBcNdAhwZ9Gn8V22tmV8qS3Xaz8+l6p+6R+oY+0lgVRvKgn3qYjMN5Lc+d5OvlaS4isXk/447T8HKQ79OpGUntOVaBpSskFGSz2RSQVGSrK3I08YMMMH8NBw/COOQEF+3NCpf3yRQVO2Id35PIiu626kTCT9k46RyocCoAK/TnfuxjJ6iX3bNVWdsfwPaP8/CG+HnQ7ewMVYgaZliq+XnAX+agJtXc+cnOYadOGu/KB5LmoNj/me4VwHR/xFsqQ95JYFdt7F4k5exYmptDQMgIvH0vgT5fKc8ygn+q/G6LaGUBp04T1B5mfwGPUyRRbzGvSyNLJu1c01dUO6T6tLlGuclTZcG+SCoYzIwlZEg==
    RUSTFS_SECRET_KEY: AgCEtsKRCxPC8HES6ffYtVq9lN2s1HXBvgPyugx3C8jOWZ6ZTV8uZRv9fKLe/hmD2d9nBDTC9+n5On21vsca88fV4DwVKo0qLYHwIshUdXiKYTuwFQhJNBPQAbR7z/kLL4AG6TrKWPPU8Z5reQKmrMC/e9aPwLSRbca6YpxJGNAvjBO1qgEVn5F2XPHfd3kwCNu44dNhQAOJKW8jhLtmWUx0gZZ+jd3NZbzJQvF2mt4VSjsVEKDtA9btQhB7QUpUfE+nPl9yzYP/qPKCDxTfE2yL6vdiccauMHFfi4pOJvsCjZ4LWZ27+JVKnlBuznBev2Fg4lNIIRjoUAgIyupXpHm+3H+VAoZH3tggIrPwdGM4Pdwodj8yjxwRjp/4LWb/HhTqxTu7lAfzPsnKrLEWesvy6RQ6mia5r1V8xqIUvYxfvEdZ5pblaZa4oHeOtTzRRLIaNKapShSvaRaZh2E51wn6hHoNRJOFnlTtfwt9m/R7108dgjHByIVE0dRvCRFN6Qf9VLVJYhvsV44+sudFfxynguwSNHYd2OqzSDhF8UN/iLRJqLNzbBC87ihe6OcVqJMYmYH/c/V/0rDQ+DVCfxW81qrVrnjoaJWZcs9xBZ4m8fPG7jodj1xQbfrxp0yc1oheOb0MQCFF5teT9DUVJ2WruoprPPi+JDKkVbJwtfszZQMkD8pYD3rM2Ot3+qd160e15BaJX7Ajld583kEv/w==
  template:
    metadata:
      name: rustfs
      namespace: rustfs
    type: Opaque
