---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-secrets
  namespace: rustfs
spec:
  encryptedData:
    access_key: AgAuWtIh1urYl/J+UlHWdpPhfVufWnMIVOwqwPwpjaqyzSTZTE+xPUU32vilR/YI7cqq8I4ZY3GU1ys4MeqvIMe8DKY+K5ewqRUKwMaodXPZzFxAMoDKM1ksiSRfPqtEyzN+EPq785GQznzv2vj856j7Rmx4twQ86BUAAbj8B4XWc/MTc8ku3VzvR5logD02xDa9gN1y5RH0lhdM4gBVA8N1tX2Ga6TIJXH2Lcv2TfAN59dhTFYgwjvVMq4OvOfHiCohjlw68FKRSLD9P94o5XypQ2mezppwlIgGZus1vFn5+ymb2SJjjV3LEhAXHtVYPjRqEAnWwVI+7ySZgXgC9286QVbF/EzY2+W+x+qD9MwuT0owT7JBgXcvbOaEs8JJoN7drYWPR7FN2+idcHJSaLqs8aVBfIxaRGYrQnxwevgKpMF9OmvBG3EaXvd/wqSqUvxjJ4OeKJi+n2ljWSCxK40ZqKleu0O6tADG/toQPyERxQgXCXh0fDam2NAcndCZVoegmx1f+RQ2pot0Zyp1QMiwvpPvH5Nly76pfgE6p5yWefm4npx61iK/Eg0LWOjFeu5B9vzqWWJ5kyd6IQwHjyDDJI3hM8jcolwud1r60uIR0D/STO4lls85cHs6YSQXMj7dw/5aC0Hck8pq3tkWzadB83tVhuvMw4Sh79U9DN1mtYKDFQwZSXOu5n6iA/08lw0vnuIeyIE4tQ==
    secret_key: AgCegwt6PK+LHnXM4MqrjzINTZGtRKtvmVKR4c8Eax2jEI0Chm5QWjzN/BSb0KcZV+qjSk2bMdSTnU7gtbja8AS9j8K18beQnHMOnCL2e5jQS1sDXJE4a34ht6oFKRNwWe+rggfaPMc9IeJ+vEdPX59NvlnVRsFe/ojyM3FCaEZtumQhLR1IzGjT6ea55qcbMJ8LRMBsbOFJhhqJi3lga5Uv008Ht/smlgOJCsRA1i0YbZFDlZ/fTGT91yGsE6kYaHSpoNwgS3oeRytg7KZtJPcWSyH7xAr/XHDDGjVoLXlw3fW9JMYhDVkN2Vj0CNnYtnowN1DqME0EX2CVqGyWNVmVzgIegF9m+ndRquqa4WvgVPjOOhUBmlFsx7iXTFctG2/uoYNIyv3pF3tXu+Th5KHtSNgKcc1itIAipAgZ5ph/z/SMj+Ogb2FfRzNhbxrsI0nqMWWc+EpmDE2/f6uevojZoXW8kV2Crtatk8tWZgx4GpTMGGcw55wFVKDS+b93D2fQ3yVV1iXPWvpHqqLcVqslClr/W+lUQ+GmG06DbnGjQjc3p3RxHbz73vsH7/EwF9ndD3uuEuzAc3+j4Z8Huf4y9boHsu6ls7x0LdWFlqgCbW3wB8wjRW3Bg6B2jEfBBqXOI6/qr9GurHEUtn4lDHElcBd/FpgPfmg39ffLA4022j0NU1gO3RzCSBngUwgMSHN7SjJQ7tt/treDBQ==
  template:
    metadata:
      name: rustfs-secrets
      namespace: rustfs
    type: Opaque
