---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAg8aiM5CL5DZpcfBvAy/be1XO4JHgLSdFVm1z5xwS1vJCJxkQ6BKRgp7WXGHSqfDQJ7TmeFRF8fjgfzDqDCkFT58SROLyHBPLNeeBROiVfL1tmQQ6UVZyxzZMFoBd4XHUrkdsugfMFvUS8vvUqVWYPaHgSJFsCQmHO0PxqegUhuVWY/Ot5er/VvHjy5URRlrAO/JwqGk8iE7VS4TJTjeLhEL/Guc+3V944chujTuegpw18LPApKfydbF648uP783pAiTqFoEFymdEDZgy0GzPMA83sK2QknO61P+pCayYS2fFXWHo8yg6MGxIYfI7kOq04w0pJaFnPFW4gtoAVWYLJjFdmdfgjPpgy5RvKQFf8Q2gPRA8ouxEXxnehi5QtSHAmQjxH5x2foNcZky6A5EZOVygt1TMV9RCZBrLj8OvPo/R2hQpMo2gBslcBcdeHfenGJUzmrdIicjQjYuYAHn602eQUKVSY+ModmBy6U6h+rGCdv7CgJk2PYWzP/+k4EGLls41mzkNJkxYMgFSYWrgPfr7Ie9Z9JR8N4EERUblxhPARomhfE08LQjIjh9iL18wuDGsu5q7uqKxlPY/eRkTy8sKct0HXNt2NWE9PcfiGxzxKKnU6LRr3YWq2rtxMq2LLf/0WWsJ0nBDk7mRq//FD2U1Ov9UwiIac/eB695rr1HXK1FuZmxibDapmCvjPfL8RCSJ7FWzQ+38YGw==
    admin-user: AgBP8+KSKWGF6gtcIANmrh9HTUHEhJ3mkg7JWbd89U3ZtD7Jd2T6LHD6140pFZnKLUkHTA/66G91WWR0BGQCFsnyteN22yIHlr9StWPerd0oFJK+91xgPcRKZZFE54IIKpssn2jYmXOHcNoNrgVO1qrBGlBhN9QOGd0+ndGB8idJ2lDg0PSUOa6r7jDqLWadMslEyokFGz2C90LozdhnJO7uWVmM6dRqNRZ13EqXfWyv7/Nv4cWEOFeJtr67ZLBxB5OZS1pAxfp3CCD6/V2QVUQeEvB4TgsdYqEvvYWAne2uV3tfWFibvruPD7Y6zOIUgv/Tybd4XvRn7+B40YzlUpBXRywn+jQo3F5BFb4/G6LZaNsjSbVM2ZtLf2aCeP+y2rMgcL+eMErHk218CKNHe6moXMTJbTqnxP5XvUJlV7eOEqucufeiIlWbjMey/FUOFXrFeJiI9BI3HiWozYYGboRl/k3cpyHN6TdbErjFCI7djE+0r11hBxcDbT0OYs1YS/gZ4AfEUPu3zglELrWgMRAMz6StfnMcVq0FwVHSFBYLOUa4Xm8kjMMglCEC6ewxXbHrp3q5rlnWNOgGzE0ldVm7hu7/moWsB2hOV2xvS05AEqC/nuIuPBHV28mj8HdCb54oCy18Mv/1HRl8JtCLb4q0PZ2hURXE6/b+sE3940UxvPxVnzcIQYT3VmAgMJFSwZ+NSFk0CoZ1Vg==
  template:
    metadata:
      name: grafana-secret
      namespace: monitoring
    type: Opaque
